"""
PDF Report Generator - Professional security report export.
Enterprise-grade: PDF, Excel, SIEM integration ready.
"""
import os
from datetime import datetime
from typing import List, Dict, Any


class PDFReportGenerator:
    """Generate professional security reports."""

    def __init__(self):
        self.reports_dir = "./outputs/reports"
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_pdf_report(self, target: str, findings: List[Any]) -> str:
        """Generate PDF security report (simplified HTML-to-PDF format)."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filename = "security_report_" + datetime.now().strftime("%Y%m%d_%H%M%S") + ".html"
        filepath = os.path.join(self.reports_dir, filename)

        # Count by severity
        critical = sum(1 for f in findings if f.severity == "critical")
        high = sum(1 for f in findings if f.severity == "high")
        medium = sum(1 for f in findings if f.severity == "medium")
        low = sum(1 for f in findings if f.severity == "low")

        findings_html = ""
        for i, f in enumerate(findings, 1):
            severity_color = {
                "critical": "#dc2626",
                "high": "#ea580c",
                "medium": "#ca8a04",
                "low": "#16a34a",
            }.get(f.severity, "#6b7280")

            findings_html += f"""
            <div style="margin-bottom: 20px; padding: 15px; border-left: 4px solid {severity_color}; background: #f8fafc;">
                <h3 style="margin: 0 0 10px 0; color: {severity_color};">
                    {i}. [{f.severity.upper()}] {getattr(f, 'owasp_id', 'VULN')}: {f.name}
                </h3>
                <p style="margin: 5px 0; color: #374151;"><strong>Description:</strong> {getattr(f, 'description', 'N/A')}</p>
                <p style="margin: 5px 0; color: #374151;"><strong>Payload:</strong> <code style="background: #e5e7eb; padding: 2px 6px; border-radius: 4px;">{getattr(f, 'payload', 'N/A')}</code></p>
                <p style="margin: 5px 0; color: #374151;"><strong>Evidence:</strong> {getattr(f, 'evidence', 'N/A')}</p>
                <p style="margin: 5px 0; color: #374151;"><strong>Remediation:</strong> {getattr(f, 'remediation', 'N/A')}</p>
            </div>
            """

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Security Report - {target}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; color: #111827; }}
                .header {{ text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e5e7eb; }}
                .summary {{ display: flex; gap: 20px; margin: 30px 0; }}
                .summary-card {{ flex: 1; padding: 20px; border-radius: 8px; text-align: center; }}
                .critical {{ background: #fef2f2; color: #dc2626; }}
                .high {{ background: #fff7ed; color: #ea580c; }}
                .medium {{ background: #fefce8; color: #ca8a04; }}
                .low {{ background: #f0fdf4; color: #16a34a; }}
                .footer {{ margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1 style="margin: 0;">LLM Security Assessment Report</h1>
                <p style="color: #6b7280; margin: 10px 0 0 0;">Target: {target}</p>
                <p style="color: #6b7280; margin: 5px 0 0 0;">Date: {timestamp}</p>
            </div>

            <div class="summary">
                <div class="summary-card critical">
                    <h2 style="margin: 0;">{critical}</h2>
                    <p style="margin: 5px 0 0 0;">Critical</p>
                </div>
                <div class="summary-card high">
                    <h2 style="margin: 0;">{high}</h2>
                    <p style="margin: 5px 0 0 0;">High</p>
                </div>
                <div class="summary-card medium">
                    <h2 style="margin: 0;">{medium}</h2>
                    <p style="margin: 5px 0 0 0;">Medium</p>
                </div>
                <div class="summary-card low">
                    <h2 style="margin: 0;">{low}</h2>
                    <p style="margin: 5px 0 0 0;">Low</p>
                </div>
            </div>

            <h2>Findings</h2>
            {findings_html}

            <div class="footer">
                <p>Generated by BlacksmithAI - LLM Security Testing Platform</p>
                <p>This report is for authorized security testing only.</p>
            </div>
        </body>
        </html>
        """

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return filepath

    def generate_json_report(self, target: str, findings: List[Any]) -> str:
        """Generate JSON report for SIEM integration."""
        import json

        report = {
            "target": target,
            "timestamp": datetime.now().isoformat(),
            "tool": "BlacksmithAI",
            "findings": [
                {
                    "id": getattr(f, 'owasp_id', 'VULN'),
                    "name": f.name,
                    "severity": f.severity,
                    "description": getattr(f, 'description', ''),
                    "payload": getattr(f, 'payload', ''),
                    "evidence": getattr(f, 'evidence', ''),
                    "remediation": getattr(f, 'remediation', ''),
                }
                for f in findings
            ],
            "summary": {
                "critical": sum(1 for f in findings if f.severity == "critical"),
                "high": sum(1 for f in findings if f.severity == "high"),
                "medium": sum(1 for f in findings if f.severity == "medium"),
                "low": sum(1 for f in findings if f.severity == "low"),
            }
        }

        filename = "security_report_" + datetime.now().strftime("%Y%m%d_%H%M%S") + ".json"
        filepath = os.path.join(self.reports_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        return filepath


# Global instance
pdf_report_generator = PDFReportGenerator()
